# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Density function of betabinomial with the shape parameterizations
#'
#' @inheritParams dbetabinom_double
#' @param alpha The first shape parameter.
#' @param beta The second shape paramter.
#'
#' @author David Gerard
dbetabinom_alpha_beta_double <- function(x, size, alpha, beta, log) {
    .Call('_mupdog_dbetabinom_alpha_beta_double', PACKAGE = 'mupdog', x, size, alpha, beta, log)
}

#' Special case of betabinomial where the beta is bernoulli mu.
#'
#' @inheritParams dbetabinom_double
#'
#' @author David Gerard
dbernbinom <- function(x, size, mu, log) {
    .Call('_mupdog_dbernbinom', PACKAGE = 'mupdog', x, size, mu, log)
}

#' The density function of the beta-binomial distribution.
#'
#' @param x The quantile.
#' @param size The total number of draws.
#' @param mu The mean of the beta.
#' @param rho The overdispersion parameter of the beta.
#' @param log A logical. Should we return the log of the
#'     density \code{TRUE} or not \code{FALSE}?
#'
#' @author David Gerard
dbetabinom_double <- function(x, size, mu, rho, log) {
    .Call('_mupdog_dbetabinom_double', PACKAGE = 'mupdog', x, size, mu, rho, log)
}

#' Density function for the betabinomial distribution parameterized
#' by the mean and the overdispersion parameter.
#'
#' This is the density function. It handles the corner cases when
#' rho is 0 or 1 in intelligible ways.
#'
#' Let \eqn{\mu} and \eqn{\rho} be the mean and overdispersion paramters.
#' Let \eqn{\alpha} and \eqn{\beta} be the usual shape parameters of
#' a beta distribution. Then we have the relation
#' \deqn{\mu = \alpha/(\alpha + \beta),}
#' and
#' \deqn{\rho = 1/(1 + \alpha + \beta).}
#' This necessarily means that
#' \deqn{\alpha = \mu (1 - \rho)/\rho,}
#' and
#' \deqn{\beta = (1 - \mu) (1 - \rho)/\rho.}
#'
#' @param x A vector of quantiles.
#' @param size A vector of sizes.
#' @param mu Either a scalar of the mean for each observation,
#'     or a vector of means of each observation, and thus
#'     the same length as \code{x} and \code{size}. This must
#'     be between 0 and 1.
#' @param rho Either a scalar of the overdispersion parameter
#'     for each observation, or a vector of overdispersion
#'     parameters of each observation, and thus the same length as
#'     \code{x} and \code{size}. This must be between 0 and 1.
#' @param log A logical vector either of length 1 or the same
#'     length as \code{x} and \code{size}. This determines whether
#'     to return the log density for all observations (in the case
#'     that its length is 1) or for each observation (in the case that
#'     its length is that of \code{x} and \code{size}).
#'
#' @author David Gerard
dbetabinom <- function(x, size, mu, rho, log) {
    .Call('_mupdog_dbetabinom', PACKAGE = 'mupdog', x, size, mu, rho, log)
}

#' Adjusts allele dosage \code{p} by the sequencing error rate \code{eps}.
#'
#' @param p The allele dosage.
#' @param eps The sequencing error rate.
#'
#' @author David Gerard
eta_double <- function(p, eps) {
    .Call('_mupdog_eta_double', PACKAGE = 'mupdog', p, eps)
}

#' Adjusts allele dosage \code{p} by the sequencing error rate \code{eps}.
#'
#' @inheritParams xi_fun
#'
#' @author David Gerard
eta_fun <- function(p, eps) {
    .Call('_mupdog_eta_fun', PACKAGE = 'mupdog', p, eps)
}

#' Adjusts allele dosage \code{p} by the sequencing error rate \code{eps} and the allele bias \code{h}.
#'
#' @param p A vector of allele dosages.
#' @param eps The sequencing error rate. Must be of length 1.
#' @param h The allele bias. Must be of length 1.
#'
#' @author David Gerard
xi_fun <- function(p, eps, h) {
    .Call('_mupdog_xi_fun', PACKAGE = 'mupdog', p, eps, h)
}

