# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Density function of betabinomial with the shape parameterizations
#'
#' @inheritParams dbetabinom_double
#' @param alpha The first shape parameter.
#' @param beta The second shape paramter.
#'
#' @author David Gerard
dbetabinom_alpha_beta_double <- function(x, size, alpha, beta, log) {
    .Call('_mupdog_dbetabinom_alpha_beta_double', PACKAGE = 'mupdog', x, size, alpha, beta, log)
}

#' Special case of betabinomial where the beta is bernoulli mu.
#'
#' @inheritParams dbetabinom_double
#'
#' @author David Gerard
dbernbinom <- function(x, size, mu, log) {
    .Call('_mupdog_dbernbinom', PACKAGE = 'mupdog', x, size, mu, log)
}

#' The density function of the beta-binomial distribution.
#'
#' @param x The quantile.
#' @param size The total number of draws.
#' @param mu The mean of the beta.
#' @param rho The overdispersion parameter of the beta.
#' @param log A logical. Should we return the log of the
#'     density \code{TRUE} or not \code{FALSE}?
#'
#' @author David Gerard
dbetabinom_double <- function(x, size, mu, rho, log) {
    .Call('_mupdog_dbetabinom_double', PACKAGE = 'mupdog', x, size, mu, rho, log)
}

#' @describeIn betabinom Density function.
dbetabinom <- function(x, size, mu, rho, log) {
    .Call('_mupdog_dbetabinom', PACKAGE = 'mupdog', x, size, mu, rho, log)
}

#' The distribution function of the betabinomial. This is generally
#' only adviseable if q is relatively small.
#'
#' @inheritParams dbetabinom_double
#' @param q A quantile.
#' @param log_p A logical. Should return the log-probability
#'     \code{TRUE} or not \code{FALSE}?
#'
#' @author David Gerard
pbetabinom_double <- function(q, size, mu, rho, log_p) {
    .Call('_mupdog_pbetabinom_double', PACKAGE = 'mupdog', q, size, mu, rho, log_p)
}

#' @describeIn betabinom Distribution function.
#'
pbetabinom <- function(q, size, mu, rho, log_p) {
    .Call('_mupdog_pbetabinom', PACKAGE = 'mupdog', q, size, mu, rho, log_p)
}

#' Adjusts allele dosage \code{p} by the sequencing error rate \code{eps}.
#'
#' @param p The allele dosage.
#' @param eps The sequencing error rate.
#'
#' @author David Gerard
eta_double <- function(p, eps) {
    .Call('_mupdog_eta_double', PACKAGE = 'mupdog', p, eps)
}

#' Adjusts allele dosage \code{p} by the sequencing error rate \code{eps}.
#'
#' @inheritParams xi_fun
#'
#' @author David Gerard
eta_fun <- function(p, eps) {
    .Call('_mupdog_eta_fun', PACKAGE = 'mupdog', p, eps)
}

#' Adjusts allele dosage \code{p} by the sequencing error rate \code{eps} and the allele bias \code{h}.
#'
#' @param p A vector of allele dosages.
#' @param eps The sequencing error rate. Must be of length 1.
#' @param h The allele bias. Must be of length 1.
#'
#' @author David Gerard
xi_fun <- function(p, eps, h) {
    .Call('_mupdog_xi_fun', PACKAGE = 'mupdog', p, eps, h)
}

#' Log-sum-exponential trick.
#'
#' @param x A vector to log-sum-exp.
#'
#' @return The log of the sum of the exponential
#'     of the elements in \code{x}.
#'
#' @author David Gerard
log_sum_exp <- function(x) {
    .Call('_mupdog_log_sum_exp', PACKAGE = 'mupdog', x)
}

